### PR TITLE
fix: unknown topic client error

### LINKED ISSUE #373: Attribute topic not found as client error
`NoClientDataForTopic` should be a client error, not a server one

[Slack conversation](https://walletconnect.slack.com/archives/C058RS0MH38/p1708401484904569?thread_ts=1708390209.207209&cid=C058RS0MH38)

### PR DESCRIPTION
**Pull request by chris13524**
# Description

Attributes unknown topic errors as client errors. Also removes a lot of unused error variants from `NotifyServerError`

Resolves #373

## How Has This Been Tested?

Not tested

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Review by geekbrother — APPROVED** [review]

**Review by nopestack — APPROVED** [review]

File: src/services/public_http_server/handlers/relay_webhook/error.rs [hunk 1]
```diff
@@ -13,9 +13,18 @@ use {
 
 #[derive(Debug, thiserror::Error)]
 pub enum RelayMessageClientError {
-    #[error("Received wc_notifyWatchSubscriptions (4010) on wrong topic: {0}")]
+    #[error("Received 4010 on wrong topic: {0}")]
     WrongNotifyWatchSubscriptionsTopic(Topic),
 
+    #[error("Received 4008 on unrecognied topic: {0}")]
```
Comment (nopestack) [inline src/services/public_http_server/handlers/relay_webhook/error.rs:19]: typo on unrecognized

File: src/services/public_http_server/handlers/relay_webhook/error.rs [hunk 2]
```diff
@@ -13,9 +13,18 @@ use {
...
+    WrongNotifyUpdateTopic(Topic),
+
+    #[error("Received 4004 on unrecognied topic: {0}")]
```
Comment (nopestack) [inline src/services/public_http_server/handlers/relay_webhook/error.rs:22]: ditto

Comment (chris13524) [reply src/services/public_http_server/handlers/relay_webhook/error.rs]: Fixed in ec80ea33f7970437604885f9ab182d9116c02463

File: src/services/public_http_server/handlers/relay_webhook/error.rs (hunk 1 above)
Comment (chris13524) [reply src/services/public_http_server/handlers/relay_webhook/error.rs]: Fixed in ec80ea33f7970437604885f9ab182d9116c02463
