### PR TITLE
fix: follow SIWE spec

### LINKED ISSUE #97: fix: follow SIWE spec

### PR DESCRIPTION
**Pull request by chris13524**
# Description

Required by https://github.com/WalletConnect/walletconnect-specs/pull/139
The identity key will no longer be in Cacao resources but in the audience.

Resolves #97 

## How Has This Been Tested?

Integration tests

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: tests/integration.rs [hunk 1]
```diff
@@ -177,24 +177,17 @@ async fn notify_properly_sending_message() {
...
+            statement: None, // TODO add statement
+            aud: did_key.clone(),
             version: cacao::Version::V1,
             nonce: "xxxx".to_owned(), // TODO
             iat: Utc::now().to_rfc3339(),
             exp: None,
             nbf: None,
             request_id: None,
-            resources: Some(vec![did_key.clone()]),
+            resources: None, // TODO add identity.walletconnect.com
```
Comment (xav) [inline tests/integration.rs:190]: what about the identity server, is it still something that will exist?

**Review by xav — APPROVED** [review]

File: tests/integration.rs (hunk 1 above)
Comment (Elyniss) [reply tests/integration.rs:190]: It's complicated
