### PR TITLE
fix: data export refactors

### LINKED ISSUE #143: chore: remove account data

### PR DESCRIPTION
**Pull request by chris13524**
# Description

Remove non-hashed account from data export for privacy reasons.

Resolves #143

## How Has This Been Tested?

Not tested

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/analytics/mod.rs [hunk 1]
```diff
@@ -61,21 +67,21 @@ impl NotifyAnalytics {
...
-            let collector = ParquetWriter::<NotifyMessage>::new(opts.clone(), exporter)?;
+            let collector = ParquetWriter::<SubscriberNotification>::new(opts.clone(), exporter)?;
             Analytics::new(collector)
         };
 
         let clients = {
             let exporter = AwsExporter::new(AwsOpts {
-                export_prefix: "notify/clients",
-                export_name: "clients",
+                export_prefix: "notify/client_updates",
```
Comment (dnul) [inline src/analytics/mod.rs:76]: `subscriber_updates` instead of `client_updates` ?

**Review by dnul — APPROVED** [review]
lgtm!

**Review by geekbrother — APPROVED** [review]
