### PR TITLE
fix: verify CACAO resources

### LINKED ISSUE #71: fix: verify CACAO resources

### PR DESCRIPTION
**Pull request by chris13524**
# Description

Forgot to verify the resources in #65. Doing that here.

Resolves #71

## How Has This Been Tested?

Locally with integration tests

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Review by Elyniss — APPROVED** [review]

File: src/auth.rs [hunk 1]
```diff
@@ -361,6 +369,14 @@ pub async fn verify_identity(pubkey: &str, keyserver: &str, account: &str) -> Re
         Err(AuthError::CacaoAccountMismatch)?;
     }
 
+    if let Some(resources) = cacao.p.resources {
+        if !resources.contains(&iss.to_owned()) {
+            Err(AuthError::CacaoResourcesMissingIss)?;
```
Comment (arein) [inline src/auth.rs:374]: Need a log statement here?

**Review by arein — APPROVED** [review]

File: src/auth.rs (hunk 1 above)
Comment (chris13524) [reply src/auth.rs:374]: wdym? It's an error which is logged up the stack
