### PR TITLE
fix: subscribe twice sends 2 welcome notifications

### LINKED ISSUE #275: bug: can get 2 welcome notifications if subscribe method called twice

### PR DESCRIPTION
**Pull request by chris13524**
# Description

Fixes that calling subscribe multiple times will send multiple welcome notifications.

Resolves #275 

## How Has This Been Tested?

Automated tests

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/services/websocket_server/handlers/notify_subscribe.rs [hunk 1]
```diff
@@ -133,41 +132,41 @@ pub async fn handle(msg: PublishedMessage, state: &AppState) -> Result<()> {
...
     info!("Timing: Finished upserting subscriber");
 
+    let notify_topic = subscriber.topic;
+
     // TODO do in same transaction as upsert_subscriber()
     state
         .notify_webhook(
-            project_id.as_ref(),
+            project.project_id.as_ref(),
+            // if subscriber.inserted {
```
Comment (geekbrother) [inline src/services/websocket_server/handlers/notify_subscribe.rs:165]: Is this comment should be uncommented?

Comment (chris13524) [inline src/services/websocket_server/handlers/notify_subscribe.rs:165]:
```suggestion
            project.project_id.as_ref(),
            // TODO uncomment when `WebhookNotificationEvent::Updated` exists
            // if subscriber.inserted {
```

Comment (chris13524) [reply src/services/websocket_server/handlers/notify_subscribe.rs:166]: No because `WebhookNotificationEvent::Updated` doesn't exist yet. The webhooks are a noop right now, so when I get the webhooks working again then this can be uncommented.

Comment (geekbrother) [reply src/services/websocket_server/handlers/notify_subscribe.rs:166]: Thanks for clarifying this.

**Review by geekbrother — APPROVED** [review]
