### PR TITLE
fix: did:key app_authentication_key

### LINKED ISSUE #152: fix: did:key app_authentication_key

### PR DESCRIPTION
**Pull request by chris13524**
# Description

`app_authentication_key` should be a `did:key` as per the [updated spec](https://github.com/WalletConnect/walletconnect-specs/pull/167).

Resolves #152 

## How Has This Been Tested?

Automated tests

## Due Diligence

* [X] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/websocket_service/handlers/notify_watch_subscriptions.rs [hunk 1]
```diff
@@ -180,17 +180,32 @@ pub async fn collect_subscriptions(
...
+    let subscriptions = {
+        let try_subscriptions = subscriptions
+            .into_iter()
+            .map(|sub| {
+                fn wrap(sub: SubscriberWithProject) -> Result<NotifyServerSubscription> {
+                    Ok(NotifyServerSubscription {
+                        app_domain: sub.app_domain,
+                        app_authentication_key: format!(
+                            "did:key:{}",
+                            DecodedClientId(decode_key(&sub.authentication_public_key)?)
```
Comment (Elyniss) [inline src/websocket_service/handlers/notify_watch_subscriptions.rs:192]: Something smells. It's not DecodedClientId, It's encoded ED25519 key. Do we have tests for this?

**Comment by Elyniss** [comment]
LGTM
