### PR TITLE
fix: switch to relay webhooks

### LINKED ISSUE #235: feat(webhooks): implement webhooks 2.0 support
Implement and test WebHooks 2.0 support on the server.

### PR DESCRIPTION
**Pull request by chris13524**
# Description

Switches from websocket client to webhooks 2.0 according to the proposed approach outlined [here](https://www.notion.so/walletconnect/How-to-allow-Notify-Server-to-horizontally-scale-bb62e58cb78946368e85bf8a0cf9c9dc?pvs=4).

Resolves #235

Depends on https://github.com/WalletConnect/notify-server/pull/343

Remaining work:
- [x] `relay_public_key` variable added to TF cloud
- [x] Verify aud
- [x] Verify iss
- [x] batchReceive messages. Blocked by https://walletconnect.slack.com/archives/C05ABTQSPFY/p1706640165101309
- [x] Re-enable unsubscribe in notifyDelete: https://walletconnect.slack.com/archives/C05ABTQSPFY/p1706307603828609
- [x] Re-implement deployment tests
- [x] New unit tests
  - [x] Registers with 30 day expiration
  - [x] Wrong `iss` is rejected in webhook handler
  - [x] batchReceive is called (i.e. fetch fails)
- [x] Update implementation to match specs: https://walletconnect.slack.com/archives/C05ABTQSPFY/p1706305922028699
- [x] Restore 4050 publishing for topics on resubscribe
- [x] Batch receive service
- [x] Merge https://github.com/WalletConnect/rs-relay/pull/1427 and use tagged version

For subsequent PRs:
- https://github.com/WalletConnect/notify-server/issues/303
- https://github.com/WalletConnect/notify-server/issues/325
- https://github.com/WalletConnect/notify-server/issues/354

## How Has This Been Tested?

Existing and new tests

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/config/deployed/mod.rs [hunk 1]
```diff
@@ -88,6 +89,7 @@ pub fn get_configuration() -> Result<Configuration, NotifyServerError> {
         keypair_seed: config.keypair_seed,
         project_id: config.project_id,
         relay_url: config.relay_url,
+        relay_public_key: config.relay_public_key,
```
Comment (heilhead) [inline src/config/deployed/mod.rs:92]: There's an endpoint in the relay to fetch the key:
https://relay.walletconnect.com/public-key

File: src/rpc.rs [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+    pub id: u64,
+    pub jsonrpc: String,
+    pub method: String,
+    pub params: T,
+}
+
+impl<T> NotifyRequest<T> {
+    pub fn new(method: &str, params: T) -> Self {
+        let id = chrono::Utc::now().timestamp_millis().unsigned_abs();
+        let id = id * 1000 + rand::thread_rng().gen_range(100, 1000);
```
Comment (heilhead) [inline src/rpc.rs:49]: Not sure it makes sense here, but you could use the [`MessageIdGenerator`](https://github.com/WalletConnect/WalletConnectRust/blob/main/relay_client/src/lib.rs#L146) from `relay_client`.

File: src/services/public_http_server/handlers/relay_webhook/mod.rs [hunk 3]
```diff
@@ -0,0 +1,199 @@
...
+        message: event.message,
+        tag: event.tag,
+    };
+
+    // TODO send to channel and process in batches
+    state
+        .relay_client
+        .batch_receive(vec![Receipt {
+            topic: incoming_message.topic.clone(),
+            message_id: serde_json::from_str("0").unwrap(), // FIXME use actual message ID
```
Comment (heilhead) [inline src/services/public_http_server/handlers/relay_webhook/mod.rs:120]: Should this be fixed as part of this PR? The relay is now sending these IDs in the payload.

File: src/services/relay_renewal_job/mod.rs [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+        &notify_url,
+        &keypair,
+        &relay_client,
+        &postgres,
+        metrics.as_ref(),
+    )
+    .await?;
+
+    Ok(async move {
+        tokio::time::sleep(interval.period()).await;
```
Comment (heilhead) [inline src/services/relay_renewal_job/mod.rs:40]: Are you sure this is needed?

File: src/services/relay_renewal_job/refresh_topic_subscriptions.rs [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+    // Limit concurrency to avoid overwhelming the relay with requests.
+    const REQUEST_CONCURRENCY: usize = 200;
+
+    futures_util::stream::iter(topics)
+        .map(|topics| {
+            // Map result to an unsized type to avoid allocation when collecting,
+            // as we don't care about subscription IDs.
+            client.batch_subscribe_blocking(topics).map_ok(|_| ())
+        })
+        .buffer_unordered(REQUEST_CONCURRENCY)
```
Comment (heilhead) [inline src/services/relay_renewal_job/refresh_topic_subscriptions.rs:62]: Can you please make sure that concurrency of all relay calls are limited to some sane number? The reason is because notify is not subject to regular rate limits, and we need to be careful with the load. Although HTTP _should in theory_ distribute the load between multiple relay nodes, my testing showed that that's not always the case.

**Review by heilhead — APPROVED** [review]
Did a shallow review, looks good! Though someone else should do an in-depth review of the business logic.

File: src/services/public_http_server/handlers/relay_webhook/mod.rs (hunk 3 above)
Comment (chris13524) [reply src/services/public_http_server/handlers/relay_webhook/mod.rs]: Yup, did in [1953773](https://github.com/WalletConnect/notify-server/pull/339/commits/1953773db51e44d2d27f9530629d86b1905bcf48)

File: src/services/relay_renewal_job/mod.rs (hunk 4 above)
Comment (chris13524) [reply src/services/relay_renewal_job/mod.rs]: Yeah it's needed since `tick()` doesn't delay the first time it's called, so doing a manual delay here.

I refactored this a little to make it more clear in 375efd973d37673ca8c6d660330fbe4de1372131

File: src/rpc.rs (hunk 2 above)
Comment (chris13524) [reply src/rpc.rs:49]: Nice, I didn't know about this. I refactored to use this in https://github.com/WalletConnect/notify-server/pull/356

File: src/services/relay_renewal_job/refresh_topic_subscriptions.rs (hunk 5 above)
Comment (chris13524) [reply src/services/relay_renewal_job/refresh_topic_subscriptions.rs:65]: The concurrency is constrained by two things:
- The rate limits from clients of Notify Server
- The concurrency limits of background jobs, such as this one here

I haven't done the math on what this results to, but endpoints allow no more than 1 req/s per client on average and currently we have about 1 req/s average from usage so we should be in the green.

Having a more global rate limiting mechanism such that we limit the absolute rate of requests across the entire service will be a complex refactor, which I would have to think more about to know how to approach. But in general this is still flawed as we being to implement horizontal scaling where we can't have such a global limit. If relay is having problems processing the request load, then relay becomes a bottleneck to the user-facing performance of Notify Server so performance must be improved in relay to support.
