### PR TITLE
fix: notify subscribe tag in integration tests

### LINKED ISSUE #55: fix: integration tests

### PR DESCRIPTION
**Pull request by chris13524**
# Description

CD integration tests were failing and I couldn't figure out why. Turns out I was using the push subscribe tag (4006) instead of the notify subscribe tag (4000) in my integration tests 🤦. Didn't see this locally when testing because my .env was configured with DEV environment which tests against the dev environment I had deployed before, of which was still running the previous version of the app that DID still allow the push subscribe tag.

Fixed the integration tests to use correct tag, and make it harder to test against non-local to prevent this issue in the future.

Resolves #55

## How Has This Been Tested?

Locally

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: tests/integration.rs [hunk 1]
```diff
@@ -181,7 +181,7 @@ async fn notify_properly_sending_message() {
         .publish(
             subscribe_topic.into(),
             message,
-            4006,
```
Comment (arein) [inline tests/integration.rs:184]: nit: maybe switch out to variable so it's easier to catch next time

**Review by arein — APPROVED** [review]

File: tests/integration.rs (hunk 1 above)
Comment (chris13524) [reply tests/integration.rs:184]: Will add in follow-up PR!

Comment (chris13524) [reply tests/integration.rs:184]: https://github.com/WalletConnect/notify-server/pull/60
