### PR TITLE
fix: SDK analytics

### LINKED ISSUE #475: feat: SDK version analytics
Add SDK version to the requests analytics: https://github.com/WalletConnect/walletconnect-specs/pull/215

### PR DESCRIPTION
**Pull request by chris13524**
# Description

Adds SDK version analytics as per [the spec](https://github.com/WalletConnect/walletconnect-specs/pull/215).

This adds a oneshot channel to transmit this information to outside of the `handle()` function which is a little strange, but seemed like a good enough solution considering the desire to have this info for both `Ok` and `Err` cases and it would be more verbose to make returning `sdk` in both cases compatible with `?`.

This also moves the validation of the JWT payloads further up in the request processing.

Resolves #475 

## How Has This Been Tested?

Not tested

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs [hunk 1]
```diff
@@ -129,6 +132,14 @@ pub async fn handle(msg: RelayIncomingMessage, state: &AppState) -> Result<(), R
             "request_auth.shared_claims.iss: {:?}",
             request_auth.shared_claims.iss
         );
+
+        request_auth
+            .validate()
+            .map_err(RelayMessageServerError::NotifyServer)?; // TODO change to client error?
```
Comment (nopestack) [inline src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs:138]: Can you elaborate on why it should be a client error?

Comment (chris13524) [reply src/services/public_http_server/handlers/relay_webhook/handlers/notify_subscribe.rs:138]: I have a bunch of these TODOs throughout the codebase, basically means "this is shitty error handling, you should re-evaluate if you can do it better".

In this case, it should be a client error because the request failed validation.
