### PR TITLE
fix: reduce logging overhead

### LINKED ISSUE #387: Remove request details and headers from HTTP req span
All the HTTP request details and headers are logged for each log entry. Change it so the method, path, and headers are only logged once, and only the x-request-id is in the span.

### PR DESCRIPTION
**Pull request by chris13524**
# Description

- Remove the headers from the request span to reduce logging cost. Only include x-request-id in request span. All other details are logged once at the beginning of request processing.
- Fix that running locally request spans would not show because log level is `WARN,notify_server=DEBUG` and the span was in an external crate
- Remove random `client_public_key` log

Resolves #387 

## How Has This Been Tested?

Locally

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/services/public_http_server/handlers/relay_webhook/mod.rs [hunk 1]
```diff
@@ -177,7 +177,7 @@ pub struct RelayIncomingMessage {
     pub tag: u32,
 }
 
-#[instrument(skip_all, fields(topic = %msg.topic, tag = %msg.tag, message_id = %get_message_id(&msg.message)))]
+#[instrument(skip_all, fields(message_id = %get_message_id(&msg.message)))]
```
Comment (geekbrother) [inline src/services/public_http_server/handlers/relay_webhook/mod.rs:180]: I don't think reducing fields should affect the CloudWatch cost here, but let's remove it if you think you don't need it.

**Review by geekbrother — APPROVED** [review]

File: src/services/public_http_server/handlers/relay_webhook/mod.rs (hunk 1 above)
Comment (chris13524) [reply src/services/public_http_server/handlers/relay_webhook/mod.rs:180]: Why not? CloudWatch charges per GB and more fields is more bytes?

Comment (nopestack) [reply src/services/public_http_server/handlers/relay_webhook/mod.rs:180]: @chris13524 is right, AWS does charge by data points, see https://aws.amazon.com/cloudwatch/pricing/

**Review by nopestack — APPROVED** [review]
