### PR TITLE
fix: assert one topic per account

### LINKED ISSUE #26: bug:  fix: multiple clients with same account subscribing to same dapp
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

If a second device with same blockchain account subscribes to the same dapp, then it will:
- Replace the existing subscription and the first device will no longer receive notifications
- It will result in abandoned data in the lookup_table collection
  - When we migrate to relational, we just need to make sure to ignore this abandoned data

Context: https://walletconnect.slack.com/archives/C04JHSB53MK/p1691757333962539

### Expected Behavior

Either the lookup_table collection is cleared, or we support multiple devices subscribing to the same dapp for the same account.

### Steps To Reproduce

Just looking at code

### Environment

- OS:
- rustc:
- cargo:

### Relevant log output

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chris13524**
# Description

Change query to query by account instead of topic. This updates the existing lookup_table entry with a new topic for an existing account, rather than making a new one for a new topic.

Goal is to prevent multiple topics from being created for the same account.

Resolves #26

## How Has This Been Tested?

Locally with tests

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Review by xav — APPROVED** [review]

**Review by Elyniss — APPROVED** [review]
LGTM!!!!!!!

File: src/types.rs [hunk 1]
```diff
@@ -29,14 +29,16 @@ pub struct RegisterBody {
...
     pub id: String,
-    pub relay_url: String,
+    pub relay_url: String, // TODO remove this, it's not read anywhere?
     pub sym_key: String,
     pub sub_auth_hash: String,
     pub expiry: u64,
-    pub ksu: String,
-    pub scope: HashSet<String>,
+    pub ksu: String,            // TODO remove?
+    pub scope: HashSet<String>, // TODO rename scope to type?
```
Comment (Elyniss) [inline src/types.rs:37]: imo, scope is good

**Review by Elyniss — APPROVED** [review]
